site_name: ModelBatch
site_description: Train many independent PyTorch models simultaneously on a single GPU using vectorized operations
site_url: https://rock-z.github.io/ModelBatch/

repo_name: rock-z/ModelBatch
repo_url: https://github.com/rock-z/ModelBatch

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
    - scheme: slate
      primary: blue
      accent: blue
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: api.md
  - Implementation Summary: IMPLEMENTATION_SUMMARY.md

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
