name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      force_build:
        description: "Force build documentation"
        required: false
        default: false

# Add permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: astral-sh/setup-uv@v3
        
      - name: Set up environment
        run: |
          uv sync --dev
          
      - name: Build documentation
        run: uv run -m mkdocs build --strict
        
      - name: Setup Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v4 